spring:
  application:
    name: lab3-spring-data
  datasource:
    url: jdbc:postgresql://localhost:49153/lab3-spring-data
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080