spring:
  application:
    name: lab3
  datasource:
    password: TEST
    url: jdbc:oracle:thin:@192.168.56.101:1521:orclcdb
    username: TEST
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
     init:
      mode: always
server:
  port: 8090
